version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086

  telegraf:
    image: telegraf:1.27
    container_name: telegraf
    ports:
      - 8092:8092/udp
      - 8094:8094
      - 8125:8125/udp
    links:
      - influxdb
    volumes:
      - ./config/telegraf.config:/etc/telegraf/telegraf.conf:ro

  chronograf:
    image: chronograf:1.10
    container_name: chronograf
    ports:
      - 8888:8888
    links:
      - influxdb

  kapacitor:
    image: kapacitor:1.6
    container_name: kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"    